name: run_tests
on:
  schedule:
  - cron: "0 4 * * *"
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: npm install
      run: npm install
    - name: run tests
      run: npx forcecmd deploy '--options={"checkOnly":true,"testLevel":"RunLocalTests","rollbackOnError":false}' --save-test-result
      env:
        FORCEPW: ${{ secrets.SALESFORCE_PASSWORD }}
